tabuada =int(input('Qual Tabuada Você Deseja Ver:'))
print("A Tabuada De {} Segue Abaixo! ".format(tabuada))
print('-' *15)
print('{:3} X 1  = {:3}'.format(tabuada,tabuada))
print('{:3} X 2  = {:3}'.format(tabuada,tabuada*2))
print('{:3} X 3  = {:3}'.format(tabuada,tabuada*3))
print('{:3} X 4  = {:3}'.format(tabuada,tabuada*4))
print('{:3} X 5  = {:3}'.format(tabuada,tabuada*5))
print('{:3} X 6  = {:3}'.format(tabuada,tabuada*6))
print('{:3} X 7  = {:3}'.format(tabuada,tabuada*7))
print('{:3} X 8  = {:3}'.format(tabuada,tabuada*8))
print('{:3} X 9  = {:3}'.format(tabuada,tabuada*9))
print('{:3} X 10 = {:4}'.format(tabuada,tabuada*10))
print('-'*15)