valor=int(input('Digite Um Valor Em Metros:'))
print('\n')
print('O Valor Digitado Em KM É: {} KM'.format(valor/1000) )
print('O Valor Digitado Em Hm É: {} Hm'.format(valor/100) )
print('O Valor Digitado Em DAM É: {}Dam'.format(valor/10))
print('O Valor Digitado Em Metros É: {} M'.format(valor))
print('O Valor Digitado Em DM É:{} Dm'.format(valor*10))
print('O Valor Digitado Em Centimentos É: {} Cm'.format(valor*100))
print('O Valor Digitado Em Milimetros É: {} Mm'.format(valor*1000))
